import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {stripTypeScriptTypes} from 'node:module';
const source=stripTypeScriptTypes(fs.readFileSync('app/api/uel-live/route.ts','utf8')).replace(/export /g,'');
function api(fetch){const c=vm.createContext({fetch,Response,AbortSignal,Intl,Date,console:{error(){}},setTimeout:fn=>{fn();}});vm.runInContext(source,c);return c;}
const game=(i,round='First qualifying round',status='FINISHED')=>({homeTeam:{internationalName:'Home'+i},awayTeam:{internationalName:'Away'+i},kickOffTime:{dateTime:'2026-09-15T18:00:00Z'},status,round:{translations:{name:{EN:round}}},score:{total:{home:2,away:0},halfTime:{home:null,away:null}},matchday:{number:1}});
test('round mapping distinguishes qualification and knockout, unverifiable halftime stays missing',()=>{const c=api();const data=[...Array.from({length:80},(_,i)=>game(i)),...Array.from({length:144},(_,i)=>game(i+80,'LEAGUE_PHASE','SCHEDULED')),game(500,'Knockout phase play-offs'),game(501,'Round of 16'),game(502,'Quarter-finals'),game(503,'Semi-finals'),game(504,'Final')];c.payload=data;const result=vm.runInContext('parseOfficialMatches(payload)',c);assert.equal(result.matches.find(f=>f.home==='Home0').half,'—');assert.equal(result.matches.find(f=>f.home==='Home0').halfSource,'unverified');assert.equal(result.matches.filter(f=>f.stage==='knockout').length,5);assert.equal(result.fixtures[0].matchday,1);assert.equal(result.fixtures[0].stage,'league');});
test('halftime is reconstructed from reconciled scorer events, own goals and goalless results',()=>{const c=api();const data=[game(0),game(1),game(2)];data[0].homeTeam.id='H';data[0].awayTeam.id='A';data[0].playerEvents={scorers:[{teamId:'H',phase:'FIRST_HALF',goalType:'GOAL'},{teamId:'H',phase:'SECOND_HALF',goalType:'GOAL'}]};data[1].score.total={home:0,away:0};data[2].homeTeam.id='H';data[2].awayTeam.id='A';data[2].score.total={home:1,away:0};data[2].playerEvents={scorers:[{teamId:'A',phase:'FIRST_HALF',goalType:'OWN'}]};c.payload=data;const rebuilt=vm.runInContext('deriveHalfTime(payload[0],2,0)',c),goalless=vm.runInContext('deriveHalfTime(payload[1],0,0)',c),ownGoal=vm.runInContext('deriveHalfTime(payload[2],1,0)',c);assert.equal(rebuilt.score,'1-0');assert.equal(rebuilt.source,'events');assert.equal(goalless.score,'0-0');assert.equal(goalless.source,'zero-zero');assert.equal(ownGoal.score,'1-0');assert.equal(ownGoal.source,'events');});
test('full pagination includes record after 240 and marks stage coverage',async()=>{const data=[...Array.from({length:80},(_,i)=>game(i)),...Array.from({length:164},(_,i)=>game(i+80,'League phase','SCHEDULED')),game(900,'Final')];let requests=0;const c=api(async url=>{requests++;const offset=Number(new URL(url).searchParams.get('offset'));return new Response(JSON.stringify(data.slice(offset,offset+80)),{headers:{'content-type':'application/json'}});});const response=await vm.runInContext('GET()',c);const body=await response.json();assert.equal(requests,4);assert.equal(body.matches.some(f=>f.stage==='knockout'),true);assert.equal(body.coverage.league,true);assert.equal(body.coverage.knockout,true);});
test('network failure returns snapshot without claiming online stage updates',async()=>{const c=api(async()=>{throw new Error('offline');});const response=await vm.runInContext('GET()',c);const body=await response.json();assert.equal(body.stale,true);assert.equal(body.matches.length>0,true);assert.deepEqual(body.coverage,{qualifying:false,league:false,knockout:false});});
