import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {stripTypeScriptTypes} from 'node:module';
const source=stripTypeScriptTypes(fs.readFileSync('app/api/uel-live/route.ts','utf8')).replace(/export /g,'');
function api(fetch){const c=vm.createContext({fetch,Response,AbortSignal,Intl,Date,console:{error(){}},setTimeout:fn=>{fn();}});vm.runInContext(source,c);return c;}
const game=(i,round='First qualifying round',status='FINISHED')=>({homeTeam:{internationalName:'Home'+i},awayTeam:{internationalName:'Away'+i},kickOffTime:{dateTime:'2026-09-15T18:00:00Z'},status,round:{translations:{name:{EN:round}}},score:{total:{home:2,away:0},halfTime:{home:null,away:null}},matchday:{number:1}});
test('round mapping distinguishes qualification and knockout, null halftime stays missing',()=>{const c=api();const data=[...Array.from({length:80},(_,i)=>game(i)),...Array.from({length:144},(_,i)=>game(i+80,'LEAGUE_PHASE','SCHEDULED')),game(500,'Knockout phase play-offs'),game(501,'Round of 16'),game(502,'Quarter-finals'),game(503,'Semi-finals'),game(504,'Final')];c.payload=data;const result=vm.runInContext('parseOfficialMatches(payload)',c);assert.equal(result.matches[0].half,'—');assert.equal(result.matches.filter(f=>f.stage==='knockout').length,5);assert.equal(result.fixtures[0].matchday,1);assert.equal(result.fixtures[0].stage,'league');});
test('full pagination includes record after 240 and marks stage coverage',async()=>{const data=[...Array.from({length:80},(_,i)=>game(i)),...Array.from({length:164},(_,i)=>game(i+80,'League phase','SCHEDULED')),game(900,'Final')];let requests=0;const c=api(async url=>{requests++;const offset=Number(new URL(url).searchParams.get('offset'));return new Response(JSON.stringify(data.slice(offset,offset+80)),{headers:{'content-type':'application/json'}});});const response=await vm.runInContext('GET()',c);const body=await response.json();assert.equal(requests,4);assert.equal(body.matches.some(f=>f.stage==='knockout'),true);assert.equal(body.coverage.league,true);assert.equal(body.coverage.knockout,true);});
test('network failure returns snapshot without claiming online stage updates',async()=>{const c=api(async()=>{throw new Error('offline');});const response=await vm.runInContext('GET()',c);const body=await response.json();assert.equal(body.stale,true);assert.equal(body.matches.length>0,true);assert.deepEqual(body.coverage,{qualifying:false,league:false,knockout:false});});
